# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: G.S.D.C. Ad Fundum
email: info@adfundum.info
description: >- # this means to ignore newlines until "baseurl:"
  Groningen Studenten Duik Club (Groningen Student Diving Association) Ad Fundum makes diving accessible and affordable
  to students.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tender-boyd-1634c3.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/logo_gray.png"
# header: "/assets/img/header.jpg"
favicon: "/assets/img/favicon.png"

instagram_username: adfundumdiving
facebook_username: gsdcadfundum

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-toc

liquid:
  error_mode: strict
  strict_filters: true

defaults:
- scope:
    path: "" # an empty string here means all files in the project
    type: pages
  values:
    toc_icon: stream
    toc_sticky: true
    header:
      overlay_image: "/assets/img/header.jpg"
      overlay_filter: 0.5

paginate: 5 # amount of posts to show
paginate_path: /posts/page:num/

atom_feed:
  hide: true

title_separator: '|'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
