baseURL = "http://example.org/"
languageCode = "en-us"
title = "G.S.D.C Ad Fundum"
theme = "hugo-clarity"


[menu]
 [[menu.main]]
    identifier = 'test'
    name = "testytest"
    url = "/test/"
 [[menu.main]]
    identifier = 'test2'
    name = "testytest2"
    url = "/test2/"


[params]
  header_image = "backgrounds/hero.jpg"
  custom_css=["style.css"]
  slogan="Making diving accessible and affordable for students"
  omit_categories = true
  about_me = true
  [params.social]
    instagram = "https://instagram.com/adfundumdiving"
    facebook = "https://www.facebook.com/gsdcadfundum"
